### ISSUE TITLE
Create list of useful APIs to use

### ISSUE THREAD

**Issue by rronakk** [rronakk/ynah#3]
Document their API Keys

**Comment by seakim** [comment]
Not using google calendar since it requires backend server.
We can use: https://kloudless.com/calendar-api/

testing email account: proj.ynah@gmail.com

API version v1
The App ID is required for adding accounts to your application. Many API requests require
at least 1 account connected, so check the /accounts endpoint below to see what accounts you have connected.
If you don't have any, use the “Connect Account” button to connect one.

Connect Account
ynah  / app id: zmVQHOAzupnvWnBxEvY7OGzBfn4ucuoksjCXQOFV9fRnBw

Authorize API Request
ynah  / API key: NZsmrqWBYVDn235GduJo3OeGEQhzwJs31diTPQrHEQFUcto2
Google calendar-proj.ynah@gmail.com
Account id: 306153678
Bearer Token: ociQIux1dHyuj9RI6ycCqukyatcWrA

Calendar API v1
POST /v1/accounts/{account_id}/cal/availability/ Find available meeting times

//**
* tested listing all calendars with account_id: 306153678
* checked it works
**//
GET /v1/accounts/{account_id}/cal/calendars/ List all calendars.


POST /v1/accounts/{account_id}/cal/calendars/ Create a Calendar

//**
* tested listing all events in the calendar with calendar_id: fcHJvai55bmFoQGdtYWlsLmNvbQ==
* checked it works
**//
GET /v1/accounts/{account_id}/cal/calendars/{calendar_id}/events/ List all events in a calendar.

POST /v1/accounts/{account_id}/cal/calendars/{calendar_id}/events/ Create an Event
DELETE /v1/accounts/{account_id}/cal/calendars/{calendar_id}/events/{id}/ Delete an Event
GET /v1/accounts/{account_id}/cal/calendars/{calendar_id}/events/{id}/ Retrieve an Event
PATCH /v1/accounts/{account_id}/cal/calendars/{calendar_id}/events/{id}/ Update an Event
DELETE /v1/accounts/{account_id}/cal/calendars/{id}/ Delete a Calendar
GET /v1/accounts/{account_id}/cal/calendars/{id}/ Retrieve a Calendar
PATCH /v1/accounts/{account_id}/cal/calendars/{id}/ Update a Calendar
